### ISSUE TITLE
Streaming use

### ISSUE THREAD

**Issue by HeChengHui** [Xiaobin-Rong/TRT-SE#1]
@Xiaobin-Rong 

I am interested in testing the online deployment using audio from my mic. How should I edit the script to allow for that? is the en/rnn/de_cache needed?

**Comment by HeChengHui** [comment]
@Xiaobin-Rong 

Thank you for the info. I am quite new to audio processing and not sure how should i do what you described. I wonder if there is an example script that i can reference?

Side question:
How is the performance of this compared to [denoiser](https://github.com/facebookresearch/denoiser)?

**Comment by Xiaobin-Rong** [comment]
@HeChengHui 

I'm sorry, but I don't have the example script you mentioned. I might update this repository later and provide a complete audio processing workflow. Perhaps you can check if there are other repositories that have already completed this process?

Regarding the second question, I believe this model performs better than denoiser and can achieve a relatively good RTF (real-time rate).

**Comment by HeChengHui** [comment]
@Xiaobin-Rong 

i will have a look around then. Thanks for your work and providing the models.
